### ISSUE TITLE
Error in smoothAndMergeSegments(getSegments(object), CORES = cores, WIGGLE = 0.1,  :    could not find function "smoothAndMergeSegments"

### ISSUE THREAD

**Issue by KKAres** [markowetzlab/CINSignatureQuantification#12]
Hello~I downloaded the R package CINSignatureQuantification from github and installed it. I got an error in the title while using the calculateFeatures() function. Don't you open some subfunctions of the package?

**Comment by KKAres** [comment]
And then I copy the code of subfunctions from your github. I got another error : **Error in { : task 2 failed - "'to' must be of length 1"**. Emmm... I found out that the specific subfunction that gave the error was:
![image](https://user-images.githubusercontent.com/55051322/195305114-adf74e49-0462-421d-b738-37e3918bc79e.png)
But I do not understand why this error appears, hope to get your help ~

**Comment by KKAres** [comment]
I solved the problem. Because the sex chromosomes in the chromosome column need to be represented by X or Y and not by a
number.

**Comment by Phil9S** [comment]
Many thanks for responding with your fix. We have an internal build with a check for chromosome format but the main branch currently does not. I will link this issue once available for your interest.
