### ISSUE TITLE
segVal from ASCAT

### ISSUE THREAD

**Issue by WangKang-Leo** [markowetzlab/CINSignatureQuantification#19]
I got segment copy from ASCAT, including nMajor and nMinor (both are integer). How can I get continuous total copy like you example? I guessed to calculate it as log2(Major copy number+ Minor copy number /ploidy of each sample)

Thanks so much
Kang

**Comment by Phil9S** [comment]
Hello,

Segmented output from ASCAT is allele-specific by default, you can generate total copy number by simply summing the copy number states of both alleles (allele A + allele B = total copy number). Conversion to any log2 scale is not advised as the copy number signatures require *absolute* copy number.

As for continuous (unrounded copy states) the data object ASCAT uses during fitting generates unrounded copy number states prior to rounding to integer. These values can be found in the `segments_raw` slot on the ASCAT R object (see [this documentation](https://github.com/VanLoo-lab/ascat/blob/bf325ddff3c1f3af93e05bbea950ec197904368d/ASCAT/R/ascat.runAscat.R)). You can use the total integer copy number states but our recommendation is to use continuous/unrounded copy number states.
