### ISSUE TITLE
RFE: provide a method / accessor to quickly extract the normalized activities

### ISSUE THREAD

**Issue by lbeltrame** [markowetzlab/CINSignatureQuantification#21]
Currently I extract  the normalized activities from a `cnobj`  produced by `quantiyCNSignatures` like this:

```
df_activity <- as.data.frame(cnobj@activities[["thresholdAct2"]])
```

An accessor here would make things much neater from an API perspective (I had to look in the examples to see how it was done).

**Comment by Phil9S** [comment]
Hi,

Currently the activities slot for the `SigQuant` class object can currently be accessed using the `getActivities()` method. This method by default returns the normalised and threshold adjusted signature activities.

```
library(CINSignatureQuantification)
cnobj<- quantifyCNSignatures(TCGA_478_Samples_SNP6_GOLD)
sigs <- getActivities(cnobj) # returns labelled matrix
```
You can access the data in the object using default R accessors then you can without having to use `[[`, as well.

```
cnobj@activities$thresholdAct2
```

Is this what you meant or did you have another suggestion as to how access the activities slot? Additionally I would be happy to improve the documentation if it is not clear.

**Comment by lbeltrame** [comment]
Thanks, I must've missed this. I haven't checked yet, but is this described in the class help? I vaguely recall looking for information and coming back empty-handed (but I might have looked in the wrong place).

**Comment by Phil9S** [comment]
Both `CNQuant` and `SigQuant` classes have help documentation including details of methods to access various slots. It could be a package version issue, a lot of the documentation wasn't included on initial release.

**Comment by lbeltrame** [comment]
Oh, I see. I think I did not update in a long time (I only did now as I started to containerize this for our pipelines). That must be it. Since it's not a real issue, I'll close this. Thanks for following up!
