### ISSUE TITLE
hg38 support

### ISSUE THREAD

**Issue by willhooper** [markowetzlab/CINSignatureQuantification#3]
Hi, 

It looks like hg19 chromosome lengths are hardcoded in this package. Would it be possible to add support for hg38? 

Thanks,
Will

**Comment by Phil9S** [comment]
Hello Will,

This should be implemented imminently with pull request #2, it is just under review now. I will link that pull request and close this issue on merge.

Many thanks,
Phil

**Comment by alhafidzhamdan** [comment]
Looking forward to this update! Thanks for looking into it @Phil9S
