### ISSUE TITLE
Confusion regarding input to the quantifyCINSignatures function

### ISSUE THREAD

**Issue by TBradley27** [markowetzlab/CINSignatureQuantification#6]
Hello,

I am trying to use this package at the moment, but I am having one or two issues:

I have an object of class `tbl_df` (from the tibble package) called `example_cn_profile` which I am trying to pass to `quantifyCNSignatures`, the first five rows are shown here:

|   chromosome  |   start  |     end | segVal | sample |
| --- | --- | --- | --- | --- |  
|    1   | 840001  | 1320000  | 5.32| sample_1|
|     1 |  1320001 |149940000  | 3.26| sample_1|
|    1| 149940001 |249210000 |  4.96 |sample_1|
|   2  |   30001| 243000000  | 2.95 |sample_1|
|  3 |    90001 | 13350000  | 2.22 |sample_1|

The command I am entering is this:

`CINSignatureQuantification::quantifyCNSignatures(object=example_cn_profile)`

Yet I am receiving this error:

`Error in 1:ncol(matSxC) : argument of length 0`

The README does not say what class object needs to be passed to `quantifyCNSignatures`

Also, the function documentation for `quantifyCNSignatures` states that a `CNQuant` object is needed as input. But this is not explained in the README

Any clarification on the input requirements for this package would be helpful

**Comment by Phil9S** [comment]
Hi Thomas,

I have fixed the input requirements for the `quantifyCNsignatures` function recently, it was previously restricted to a `data.frame` signature, which is perhaps incompatible with a `tbl_df`. Could you try and install the most recent version of the main branch and re-run with your data and with and without converting your data to a `data.frame` data type.

The error likely stems from the [calculateSampleByComponentMatrixDrews.R](https://github.com/markowetzlab/CINSignatureQuantification/blob/d5bdf056c849dabb77a36b90518a6a69843ad5e2/R/calculateSampleByComponentMatrixDrews.R) function but it shouldn't get that far if the input is wrong. Could you attach a longer version of your input (5-10 complete samples) so I can see if I can reproduce the error?

**Comment by TBradley27** [comment]
Hi Phil,

So I am on the latest commit (i.e. [d5bdf05](https://github.com/markowetzlab/CINSignatureQuantification/commit/d5bdf056c849dabb77a36b90518a6a69843ad5e2)).

I think the issue is that I tried to run the function using only one sample. When I used rbind to aggregate 5 copy number profiles together the function completed successfully. This was using data in `tibble` format. I encountered the same error with the 1 sample data frame with a direct `data.frame` object

So I am pretty sure it is the use of a single sample which is the issue here

**Comment by Phil9S** [comment]
Thanks, Thomas.

I've replicated the issue using a single sample as you described, I will look to fix it.

**Comment by Phil9S** [comment]
I've implemented a fix for inputting a single sample for either the drews or mac method (though `plotActivities()` does not behave correctly for a single sample). Can you pull the linked pull request #9 (branch bug-sample-n-requirements) and see if it resolves your issue?

Also, I have made some minor changes to the `clinpredictplatinum()` function during this, including updating how it retrieves the model data to match the rest of the package so that may solve issue #8 as well.

**Comment by TBradley27** [comment]
Thanks,

I am testing on the branch `bug-sample-n-requirements`. This has fixed #8 but not #6 I am afraid.

I am happy to send you my example segmentation table if that would help?

**Comment by Phil9S** [comment]
Please do, I do not encounter any errors inputting a segment table containing only a single sample.

**Comment by TBradley27** [comment]
Ah, actually no need. The reason I wasn't seeing a fix in #6 is because I forgot to restart my RStudio environment with the new repo branch. I can confirm that this pull request also fixes #6

Thank you

**Comment by Phil9S** [comment]
Thanks Thomas, your help is appreciated. I will review everything and then merge.
