### ISSUE TITLE
Confusion regarding four output signature activity matrices

### ISSUE THREAD

**Issue by TBradley27** [markowetzlab/CINSignatureQuantification#7]
Hello again,

Within the resultant `SigQuant` object after running `quantifyCNSignatures` there are four signature activity matrices that comprise the `activities` slot. 

These are `rawAct0`, `normAct1`, `thresholdAct2`, and `scaledAct3`

The first three are fairly intuitive from reading the paper. I am not 100% sure though how the scaling is done for `scaledAct3` - is this scaling done internally within the data submitted by the user, or is some external information used here for the scaling?

The documentation for `quantifyCNSignatures` does not provide information relating to these output values

**Comment by Phil9S** [comment]
The documentation, in general, requires an overhaul which will be rectified soon.

Scaling is done using the [applyThresholdNormAndScaling()](https://github.com/markowetzlab/CINSignatureQuantification/blob/5ddd778c0d14cb19dab64ae8611a2b4b85f4f40d/R/applyThreshNormAndScaling.R#L17-L20) which calls [scaleByModel()](https://github.com/markowetzlab/CINSignatureQuantification/blob/main/R/scaleByModel.R). This uses the mean and scaling factor derived from the Drews _et al._ 2022 [publication](https://www.nature.com/articles/s41586-022-04789-9#Sec17) to re-scale the signature distributions to reflect those found in the paper.

@Martingales could you confirm what I've said is correct?

**Comment by TBradley27** [comment]
Thank you Phil

So from reading the paper, I guess this refers to the 6335 TCGA SNP array samples with detectable CIN? And we are centring and scaling (individually for each CN signature) using the mean and standard deviation respectively from this sample cohort?

**Comment by Martingales** [comment]
Yes, exactly! The `scaledAct3` is the matrix that puts the signature activity of new samples in the same activity space as the TCGA samples. The idea is to allow the users to compare new samples directly with the published TCGA samples. 

Given that the signature activities are based on features they can be a bit harder to interpret. That is why we recommend comparing them to the TCGA samples and the tissue type of interest. 

Hope that clarifies things! Please reopen if you have other questions.
